var express = require('express');
var router = express.Router();

const itemList = [
  { 'id':1, 
  'term': 'DevOps', 
  'description': 'DevOps is a set of practices, tools, and a cultural philosophy that automate and integrate the processes between software development and IT teams. It emphasizes team empowerment, cross-team communication and collaboration, and technology automation.', 
  'reference': 'Atlassian. “What Is DevOps? | Atlassian.” Atlassian, 2016, www.atlassian.com/devops.'},
  { 'id':2, 
  'term': 'GitHub', 
  'description': 'GitHub is a website and cloud-based service that helps developers store and manage their code, as well as track and control changes to their code.', 
  'reference': 'Jackson, Brian. “What Is GitHub? A Beginners Introduction To...” Kinsta Managed WordPress Hosting, Kinsta Managed WordPress Hosting, 20 Apr. 2018, kinsta.com/knowledgebase/what-is-github/.'},
  { 'id':3, 
  'term': 'Node.js ', 
  'description': 'Node.js is a cross-platform, open-source server environment that can run on Windows, Linux, Unix, macOS, and more. Node.js is a back-end JavaScript runtime environment, runs on the V8 JavaScript Engine, and executes JavaScript code outside a web browser. ', 
  'reference': 'https://en.wikipedia.org/wiki/Node.js'},
  { 'id':4, 
  'term': 'JavaScript', 
  'description': 'JavaScript is a scripting or programming language that allows you to implement complex features on web pages ', 
  'reference': 'Mozilla. “What Is JavaScript?” MDN Web Docs, 2 July 2019, developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript. '},
  { 'id':5, 
  'term': 'Docker', 
  'description': 'Docker is a software platform that allows you to build, test, and deploy applications quickly.', 
  'reference': 'AWS. “What Is Docker? | AWS.” Amazon Web Services, Inc., 2019, aws.amazon.com/docker/.'},
  { 'id':6, 
  'term': 'Microservices ',
  'description': 'Microservices are an architectural and organizational approach to software development where software is composed of small independent services that communicate over well-defined APIs. These services are owned by small, self-contained teams.', 
  'reference': 'AWS. “What Are Microservices? | AWS.” Amazon Web Services, Inc., 2019, aws.amazon.com/microservices/.'},
  { 'id':7, 
  'term': 'CI/CD', 
  'description': 'CI/CD is a method to frequently deliver apps to customers by introducing automation into the stages of app development. The main concepts attributed to CI/CD are continuous integration, continuous delivery, and continuous deployment. CI/CD is a solution to the problems integrating new code can cause for development and operations teams ', 
  'reference': 'Redhat. “What Is CI/CD?” Redhat.com, 2019, www.redhat.com/en/topics/devops/what-is-ci-cd.'},
  { 'id':8, 
  'term': 'Agile', 
  'description': 'The Agile methodology is a project management approach that involves breaking the project into phases and emphasizes continuous collaboration and improvement. Teams follow a cycle of planning, executing, and evaluating. ', 
  'reference': 'Atlassian. “Agile Best Practices and Tutorials | Atlassian.” Atlassian, 2019, www.atlassian.com/agile. '},
  { 'id':9, 
  'term': 'Git ', 
  'description': 'Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. Git is easy to learn and has a tiny footprint with lightning fast performance. It outclasses SCM tools like Subversion, CVS, Perforce, and ClearCase with features like cheap local branching, convenient staging areas, and multiple workflows.', 
  'reference': 'Git. “Git.” Git-Scm.com, 2019, git-scm.com/.'},
  { 'id':10, 
  'term': 'Visual Studio Code', 
  'description': 'Visual Studio Code is a free, lightweight but powerful source code editor that runs on your desktop and on the web and is available for Windows, macOS, Linux, and Raspberry Pi OS. ', 
  'reference': 'Heller, Martin. “What Is Visual Studio Code? Microsoft’s Extensible Code Editor.” InfoWorld, 8 July 2022, www.infoworld.com/article/3666488/what-is-visual-studio-code-microsofts-extensible-code-editor.html.'},
  { 'id':11, 
  'term': 'Microservices application', 
  'description': 'A microservices application is traditionally known as a distributed application, a system composed of tiny components that live in separate processes and communicate via the network.', 
  'reference': 'Davis, Ashley. Bootstrapping Microservices with Docker, Kubernetes, and Terraform : A Project-Based Guide, Manning Publications Co. LLC, 2021. ProQuest Ebook Central, http://ebookcentral.proquest.com/lib/deakin/detail.action?docID=6642516.'},
  { 'id':12, 
  'term': 'behaviour-driven design(BDD)', 
  'description': 'Behavior-driven development (BDD) is an Agile software development methodology in which an application is documented and designed around the behavior a user expects to experience when interacting with it.', 
  'reference': 'Laura Fitzgibbons. “What Is Behavior-Driven Development (BDD)? Definition from SearchSoftwareQuality.” SearchSoftwareQuality, www.techtarget.com/searchsoftwarequality/definition/Behavior-driven-development-BDD.'},
  { 'id':13, 
  'term': 'test-driven design(TDD)', 
  'description': 'Test Driven Development (TDD) is a software development practice that focuses on creating unit test cases before developing the actual code. It is an iterative approach combining programming, unit test creation, and refactoring.', 
  'reference': 'Unadkat, Jash . “Test Driven Development (TDD) : Approach & Benefits.” BrowserStack, 15 Jan. 2021, www.browserstack.com/guide/what-is-test-driven-development.'},
  { 'id':14, 
  'term': 'CI server', 
  'description': 'A CI server (or build server) plays a key role in implementing and managing the whole process. It serves as the glue that brings all the stages of the pipeline together by applying your business logic to coordinate automated tasks and collating and publishing feedback.', 
  'reference': '“What Is a CI Server? | CI/CD Build Servers.” JetBrains, www.jetbrains.com/teamcity/ci-cd-guide/ci-cd-tools/servers/. Accessed 4 Aug. 2023.'},
  { 'id':15, 
  'term': 'Command Line Interfaces(CLI)', 
  'description': 'A command-line interface (CLI) is a means of interacting with a device or computer program with commands from a user or client, and responses from the device or program, in the form of lines of text.', 
  'reference': 'Wikipedia Contributors. “Command-Line Interface.” Wikipedia, Wikimedia Foundation, 13 Nov. 2019, en.wikipedia.org/wiki/Command-line_interface.'},
  { 'id':16, 
  'term': 'Enterprise system', 
  'description': 'Enterprise systems are large-scale software packages that are able to track and control all of the complex operations of a business.', 
  'reference': 'The University of Scranton. “10 Ways Enterprise Systems Affect Your Business.” The University of Scranton, 27 Apr. 2021, elearning.scranton.edu/resources/article/10-ways-enterprise-systems-affect-your-business/.'},
  { 'id':17, 
  'term': 'DevOps Cycle', 
  'description': 'The DevOps lifecycle is a continuous software development process that employs DevOps best practices to plan, build, integrate, deploy, monitor, operate, and offer continuous feedback throughout the softwares cycle.', 
  'reference': '“DevOps Lifecycle : Different Phases in DevOps.” BrowserStack, www.browserstack.com/guide/devops-lifecycle.'},
  { 'id':18, 
  'term': 'Deployment', 
  'description': 'Software deployment includes all of the steps, processes, and activities that are required to make a software system or update available to its intended users. Today, most IT organizations and software developers deploy software updates, patches and new applications with a combination of manual and automated processes. ', 
  'reference': 'Sumo Logic. “What Is Software Deployment? | Sumo Logic.” Sumo Logic, www.sumologic.com/glossary/software-deployment/.'},
  { 'id':19, 
  'term': 'Waterfall model', 
  'description': 'The Waterfall Model was the first Process Model to be introduced. It is also referred to as a linear-sequential life cycle model. It is very simple to understand and use. In a waterfall model, each phase must be completed before the next phase can begin and there is no overlapping in the phases.', 
  'reference': 'Tutorialspoint. “SDLC Waterfall Model.” Www.tutorialspoint.com, 2019, www.tutorialspoint.com/sdlc/sdlc_waterfall_model.htm.'},
  { 'id':20, 
  'term': 'Repository', 
  'description': 'A repository is a central location for storing and managing software code and files. It enables version control, collaboration, and history tracking of changes, making it essential for software projects.', 
  'reference': '“Repository (Version Control).” Wikipedia, 29 Mar. 2023, en.wikipedia.org/wiki/Repository_(version_control). Accessed 4 Aug. 2023.'},
  { 'id':21, 
  'term': 'Filesystem', 
  'description': 'stores and organizes data and can be thought of as a type of index for all the data contained in a storage device.', 
  'reference': 'Sullivan, E 2018, What is a File System?, SearchStorage.'},
  { 'id':22, 
  'term': 'Bridge network driver', 
  'description': 'In terms of networking, a bridge network is a Link Layer device which forwards traffic between network segments. A bridge can be a hardware device or a software device running within a host machines kernel.', 
  'reference': 'Ferdous, F 2022, The Bridge Network Driver | Networking in Docker #6, TechMormo, viewed 27 August 2023, <https://medium.com/techmormo/the-bridge-network-driver-networking-in-docker-6-af4e9809a14d>.'},
  { 'id':23, 
  'term': 'overlay network', 
  'description': 'The overlay network driver creates a distributed network among multiple Docker daemon hosts. This network sits on top of (overlays) the host-specific networks, allowing containers connected to it (including swarm service containers) to communicate securely when encryption is enabled. Docker transparently handles routing of each packet to and from the correct Docker daemon host and the correct destination container.', 
  'reference': 'Overlay network driver 2023, Docker Documentation, viewed 27 August 2023, <https://docs.docker.com/network/drivers/overlay/>.'},
  { 'id':24, 
  'term': 'macvlan network', 
  'description': 'macvlan is a local scope network driver which is configured per-host. As a result, there are stricter dependencies between MACVLAN and external networks, which is both a constraint and an advantage that is different from overlay or bridge.', 
  'reference': 'Bhardwaj, R 2021, What is MacVLAN? Detailed Expalnation - IP With Ease, ipwithease.com, viewed 27 August 2023, <https://ipwithease.com/what-is-macvlan/>.'},
  { 'id':25, 
  'term': 'Synchronous Communication', 
  'description': 'Synchronous communication happens  in real time, where at least two individuals are exchanging information, at the same time with each other. That not to say that you need to be communicating in person for this to be deemed synchronous communication.', 
  'reference': 'Fellow.app 2020, Synchronous vs. Asynchronous Communication: A Guide For Managers, Fellow.app.'},
  { 'id':26, 
  'term': 'Asynchronous Communication', 
  'description': 'asynchronous communication is communication that doesnot happen in real-time (e.g. on the phone, in-person, or during a live video conferencing meeting). For instance, in the above example, your coworker is busy and cant properly comprehend the information you are providing when you visit her desk.', 
  'reference': 'Barron, S 2020, What Is Asynchronous Communication & How Do You Use It?, resources.owllabs.com.'},
  { 'id':27, 
  'term': 'Loosely coupled', 
  'description': ' loosely coupled is an attribute of systems, referring to an approach to designing interfaces across modules to reduce the interdependencies across modules or components – in particular, reducing the risk that changes within one module will create unanticipated changes within other modules.', 
  'reference': 'Hagel, J 2002, Loosely Coupled: A Term Worth Understanding – John Hagel, Johnhagel.com.'},
  { 'id':28, 
  'term': 'Container Communication', 
  'description': 'Container networking allows containers to communicate with other containers or hosts to share resources and data. Modern container networking aims to standardize and optimize container data flows, creating zones of isolation that allow large numbers of containers to communicate in an efficient and secure manner.', 
  'reference': 'Container Networking n.d., Tigera.https://www.tigera.io/learn/guides/kubernetes-networking/container-networking/'},
  { 'id':29, 
  'term': 'Docker Compose ', 
  'description': 'Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your applications services. Then, with a single command, you create and start all the services from your configuration.', 
  'reference': 'Docker Compose (2022) [website] https://docs.docker.com/compose/'},
  { 'id':30, 
  'term': 'YAML', 
  'description': 'YAML is a human-readable data serialization language that is often used for writing configuration files.', 
  'reference': 'What is YAML? 2023, www.redhat.com.'},
  { 'id':31, 
  'term': 'Kubernetes', 
  'description': 'Kubernetes is a portable, extensible, open source platform for managing containerized workloads and services, that facilitates both declarative configuration and automation. It has a large, rapidly growing ecosystem. Kubernetes services, support, and tools are widely available.', 
  'reference': 'kubernetes. (2023, July 16). Overview. Kubernetes. https://kubernetes.io/docs/concepts/overview/'},
  { 'id':32, 
  'term': 'Kubernetes Components', 
  'description': 'A Kubernetes cluster consists of a set of worker machines, called nodes, that run containerized applications. Every cluster has at least one worker node.', 
  'reference': 'kubernetes. (2022, October 24). Kubernetes Components. Kubernetes. https://kubernetes.io/docs/concepts/overview/components/'},
  { 'id':33, 
  'term': 'Terraform', 
  'description': 'Terraform is an infrastructure as code tool that lets you define both cloud and on-prem resources in human-readable configuration files that you can version, reuse, and share. You can then use a consistent workflow to provision and manage all of your infrastructure throughout its lifecycle. Terraform can manage low-level components like compute, storage, and networking resources, as well as high-level components like DNS entries and SaaS features.', 
  'reference': 'Hashicorp. (n.d.). What is Terraform | Terraform | HashiCorp Developer. What Is Terraform | Terraform | HashiCorp Developer. https://developer.hashicorp.com/terraform/intro'},
  { 'id':34, 
  'term': 'Hashicorp', 
  'description': 'HashiCorp Vault is a tool that allows you to safely manage secrets. By secrets, we mean sensitive information like digital certificates, database credentials, passwords, and API encryption keys. HashiCorp Vault gives you a way to store these secrets and then authenticates, validates, and authorises before it grants access to clients and users.', 
  'reference': 'Bournhonesque, P. (n.d.). What is HashiCorp Vault and What Can I Do With It? Devoteam. Retrieved September 7, 2023, from https://www.devoteam.com/expert-view/what-is-hashicorp-vault-and-what-can-i-do-with-it/'},
  { 'id':35, 
  'term': 'Variables', 
  'description': 'A variable is any characteristic, number, or quantity that can be measured or counted. A variable may also be called a data item. Age, sex, business income and expenses, country of birth, capital expenditure, class grades, eye colour and vehicle type are examples of variables. It is called a variable because the value may vary between data units in a population, and may change in value over time.', 
  'reference': 'Australian Bureau of Statistics. (2023, February 2). Variables | Australian Bureau of Statistics. Www.abs.gov.au. https://www.abs.gov.au/statistics/understanding-statistics/statistical-terms-and-concepts/variables'},
  { 'id':36, 
  'term': 'HCL', 
  'description': 'HashiCorp Configuration Language (HCL) is a unique configuration language. It was designed to be used with HashiCorp tools, notably Terraform, but HCL has expanded as a more general configuration language. It’s visually similar to JSON with additional data structures and capabilities built-in.', 
  'reference': 'Deploy, O. (2021, July 21). Introduction to HCL and HCL tooling. Octopus Deploy. https://octopus.com/blog/introduction-to-hcl-and-hcl-tooling'},
  { 'id':37, 
  'term': 'Local networks', 
  'description': 'A local area network (LAN) is a collection of devices connected together in one physical location, such as a building, office, or home. A LAN can be small or large, ranging from a home network with one user to an enterprise network with thousands of users and devices in an office or school.', 
  'reference': 'CISCO. (2019, October). What is a LAN? Local Area Network. Cisco. https://www.cisco.com/c/en/us/products/switches/what-is-a-lan-local-area-network.html'},
  { 'id':38, 
  'term': 'Cloud-native Applications', 
  'description': 'A cloud-native application is a program that is designed for a cloud computing architecture. These applications are run and hosted in the cloud and are designed to capitalize on the inherent characteristics of a cloud computing software delivery model. A native app is software that is developed for use on a specific platform or device.', 
  'reference': 'Lutkevich, B. (2021, July). What is a Cloud-Native Application and How Do You Build One? SearchCloudComputing. https://www.techtarget.com/searchcloudcomputing/definition/cloud-native-application'},
  { 'id':39, 
  'term': 'computer Cluster', 
  'description': 'A computer cluster is a set of connected computers that perform as a single system. These computers are basic units of a much bigger system, which is called a node. ', 
  'reference': 'Binders, A. (2021, April 16). What is a Computer Cluster? Liquid Web. https://www.liquidweb.com/blog/computer-cluster/'},
  { 'id':40, 
  'term': 'Container Applications', 
  'description': 'Containerized applications are applications that run in isolated runtime environments called containers. Containers encapsulate an application with all its dependencies, including system libraries, binaries, and configuration files. This all-in-one packaging makes a containerized application portable by enabling it to behave consistently across different hosts—allowing developers to write once and run almost anywhere.', 
  'reference': 'Datadog. (2022, February 16). What Are Containerized Applications? | Datadog. What Are Containerized Applications? https://www.datadoghq.com/knowledge-center/containerized-applications/'},
  { 'id':41, 
'term': 'bitbucket', 
'description': 'BitBucket is a cloud-based service that helps developers store and manage their code, as well as track and control the changes to their code. BitBucket provides a cloud-based Git repository hosting service.', 
'reference': 'arjunbharti774. (2020, April 6). Introduction to BitBucket. GeeksforGeeks. https://www.geeksforgeeks.org/introduction-to-bitbucket/'},
{ 'id':42, 
'term': 'deployment pipeline', 
'description': 'deployment pipeline is is a set of automated processes that allow developers and DevOps professionals to reliably and efficiently compile, build, and deploy their code to their production compute platforms. ', 
'reference': 'Merron, D. (2018). What is a Pipeline in Software Engineering? Intro to Deployment, CI, & CD Pipelines. BMC Blogs. https://www.bmc.com/blogs/deployment-pipeline/'},
{ 'id':43, 
'term': ' code repository', 
'description': 'A code repository is an archive of the code that is being worked on. Beyond the code itself, you can keep things such as documentation, notes, web pages, and other items in your repository. A code repository is required for any successful software development project.', 
'reference': 'Pawlan, D. (2022). What is a Code Repository? Best Code Repo Hosting in 2021 (Updated for 2022) | The Aloa Blog. Aloa.co. https://aloa.co/blog/what-is-code-repository-best-code-repo-hosting-2021'},
{ 'id':44, 
'term': 'rollouts and rollbacks ', 
'description': 'a rollout is the process of updating a running application by deploying a new version of the application. The new version is typically deployed in a phased manner, so that if any issues are discovered, they can be addressed before the entire application is updated.A rollback, on the other hand, is the process of undoing a rollout and reverting back to a previous version of the application. Rollbacks are important because they allow developers to quickly and easily undo changes that have caused issues in production.', 
'reference': 'Wagner, G. (2023, February 27). How does Kubernetes Perform a deployment Rollout and Rollback? A DevOps Blog. https://www.valewood.org/kubernetes-how-rollout-and-rollbacks-are-performed/#rollouts-and-rollbacks'},
{ 'id':45, 
'term': 'continuous integration', 
'description': 'Continuous integration is the practice of automating the integration of code changes from multiple contributors into a single software project. It’s a primary DevOps best practice, allowing developers to frequently merge code changes into a central repository where builds and tests then run. ', 
'reference': 'Atlassian. (2019). What is Continuous Integration | Atlassian. Atlassian. https://www.atlassian.com/continuous-delivery/continuous-integration'},
{ 'id':46, 
'term': 'Automate the build', 
'description': 'The Build is preparing and turning your source code into executable software. It can include compilation, file compression, the packaging of assets, updating database schema, creating an installer or executable file, signing with a certificate, testing, and more. ', 
'reference': 'Chatterjee, S. (2023, March 14). Build Automation: Everything you Need to Know. BrowserStack. https://www.browserstack.com/guide/build-automation'},
{ 'id':47, 
'term': 'Regression test', 
'description': 'Regression Testing is a type of testing in the software development cycle that runs after every change to ensure that the change introduces no unintended breaks. Regression testing addresses a common issue that developers face — the emergence of old bugs with the introduction of new changes.', 
'reference': 'Daityari, S. (2023, June 24). Regression Testing : Definition, How it works. BrowserStack. https://www.browserstack.com/guide/regression-testing'},
{ 'id':48, 
'term': 'Security test', 
'description': 'Security Testing is a type of Software Testing that uncovers vulnerabilities, threats, risks in a software application and prevents malicious attacks from intruders. ', 
'reference': 'Hamilton, T. (2019, December 4). What is Security Testing? Types with Example. Guru99.com. https://www.guru99.com/what-is-security-testing.html'},
{ 'id':49, 
'term': 'End-to-end Testing', 
'description': 'End-to-end testing is a fascinating technique as it is often used in agile and many other testing methodologies, but it is still not easy to understand.', 
'reference': 'Shreya Bose, S., & Contributor, C. (2023, February 20). End To End Testing: A Detailed Guide. BrowserStack. https://www.browserstack.com/guide/end-to-end-testing'},
{ 'id':50, 
'term': 'Unit Testing', 
'description': 'Unit testing is a software development process in which the smallest testable parts of an application, called units, are individually scrutinized for proper operation. ', 
'reference': 'Contributor, T. (2023, May). What is Unit Testing? Definition from WhatIs.com. SearchSoftwareQuality. https://www.techtarget.com/searchsoftwarequality/definition/unit-testing'},

  
];

/*
{ 'id':, 
'term': '', 
'description': '', 
'reference': ''},
*/

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', subtitle: 'Software Deployment and Operations Glossary', items: itemList });
});

module.exports = router;
