var express = require('express');
var router = express.Router();

const itemList = [
  { 'id':1, 
  'term': 'DevOps', 
  'description': 'DevOps is a set of practices, tools, and a cultural philosophy that automate and integrate the processes between software development and IT teams. It emphasizes team empowerment, cross-team communication and collaboration, and technology automation.', 
  'reference': 'Atlassian. “What Is DevOps? | Atlassian.” Atlassian, 2016, www.atlassian.com/devops.'},
  { 'id':2, 
  'term': 'GitHub', 
  'description': 'GitHub is a website and cloud-based service that helps developers store and manage their code, as well as track and control changes to their code.', 
  'reference': 'Jackson, Brian. “What Is GitHub? A Beginners Introduction To...” Kinsta Managed WordPress Hosting, Kinsta Managed WordPress Hosting, 20 Apr. 2018, kinsta.com/knowledgebase/what-is-github/.'},
  { 'id':3, 
  'term': 'Node.js ', 
  'description': 'Node.js is a cross-platform, open-source server environment that can run on Windows, Linux, Unix, macOS, and more. Node.js is a back-end JavaScript runtime environment, runs on the V8 JavaScript Engine, and executes JavaScript code outside a web browser. ', 
  'reference': 'https://en.wikipedia.org/wiki/Node.js'},
  { 'id':4, 
  'term': 'JavaScript', 
  'description': 'JavaScript is a scripting or programming language that allows you to implement complex features on web pages ', 
  'reference': 'Mozilla. “What Is JavaScript?” MDN Web Docs, 2 July 2019, developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript. '},
  { 'id':5, 
  'term': 'Docker', 
  'description': 'Docker is a software platform that allows you to build, test, and deploy applications quickly.', 
  'reference': 'AWS. “What Is Docker? | AWS.” Amazon Web Services, Inc., 2019, aws.amazon.com/docker/.'},
  { 'id':6, 
  'term': 'Microservices ',
  'description': 'Microservices are an architectural and organizational approach to software development where software is composed of small independent services that communicate over well-defined APIs. These services are owned by small, self-contained teams.', 
  'reference': 'AWS. “What Are Microservices? | AWS.” Amazon Web Services, Inc., 2019, aws.amazon.com/microservices/.'},
  { 'id':7, 
  'term': 'CI/CD', 
  'description': 'CI/CD is a method to frequently deliver apps to customers by introducing automation into the stages of app development. The main concepts attributed to CI/CD are continuous integration, continuous delivery, and continuous deployment. CI/CD is a solution to the problems integrating new code can cause for development and operations teams ', 
  'reference': 'Redhat. “What Is CI/CD?” Redhat.com, 2019, www.redhat.com/en/topics/devops/what-is-ci-cd.'},
  { 'id':8, 
  'term': 'Agile', 
  'description': 'The Agile methodology is a project management approach that involves breaking the project into phases and emphasizes continuous collaboration and improvement. Teams follow a cycle of planning, executing, and evaluating. ', 
  'reference': 'Atlassian. “Agile Best Practices and Tutorials | Atlassian.” Atlassian, 2019, www.atlassian.com/agile. '},
  { 'id':9, 
  'term': 'Git ', 
  'description': 'Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. Git is easy to learn and has a tiny footprint with lightning fast performance. It outclasses SCM tools like Subversion, CVS, Perforce, and ClearCase with features like cheap local branching, convenient staging areas, and multiple workflows.', 
  'reference': 'Git. “Git.” Git-Scm.com, 2019, git-scm.com/.'},
  { 'id':10, 
  'term': 'Visual Studio Code', 
  'description': 'Visual Studio Code is a free, lightweight but powerful source code editor that runs on your desktop and on the web and is available for Windows, macOS, Linux, and Raspberry Pi OS. ', 
  'reference': 'Heller, Martin. “What Is Visual Studio Code? Microsoft’s Extensible Code Editor.” InfoWorld, 8 July 2022, www.infoworld.com/article/3666488/what-is-visual-studio-code-microsofts-extensible-code-editor.html.'},
  { 'id':11, 
  'term': 'Microservices application', 
  'description': 'A microservices application is traditionally known as a distributed application, a system composed of tiny components that live in separate processes and communicate via the network.', 
  'reference': 'Davis, Ashley. Bootstrapping Microservices with Docker, Kubernetes, and Terraform : A Project-Based Guide, Manning Publications Co. LLC, 2021. ProQuest Ebook Central, http://ebookcentral.proquest.com/lib/deakin/detail.action?docID=6642516.'},
  { 'id':12, 
  'term': 'behaviour-driven design(BDD)', 
  'description': 'Behavior-driven development (BDD) is an Agile software development methodology in which an application is documented and designed around the behavior a user expects to experience when interacting with it.', 
  'reference': 'Laura Fitzgibbons. “What Is Behavior-Driven Development (BDD)? Definition from SearchSoftwareQuality.” SearchSoftwareQuality, www.techtarget.com/searchsoftwarequality/definition/Behavior-driven-development-BDD.'},
  { 'id':13, 
  'term': 'test-driven design(TDD)', 
  'description': 'Test Driven Development (TDD) is a software development practice that focuses on creating unit test cases before developing the actual code. It is an iterative approach combining programming, unit test creation, and refactoring.', 
  'reference': 'Unadkat, Jash . “Test Driven Development (TDD) : Approach & Benefits.” BrowserStack, 15 Jan. 2021, www.browserstack.com/guide/what-is-test-driven-development.'},
  { 'id':14, 
  'term': 'CI server', 
  'description': 'A CI server (or build server) plays a key role in implementing and managing the whole process. It serves as the glue that brings all the stages of the pipeline together by applying your business logic to coordinate automated tasks and collating and publishing feedback.', 
  'reference': '“What Is a CI Server? | CI/CD Build Servers.” JetBrains, www.jetbrains.com/teamcity/ci-cd-guide/ci-cd-tools/servers/. Accessed 4 Aug. 2023.'},
  { 'id':15, 
  'term': 'Command Line Interfaces(CLI)', 
  'description': 'A command-line interface (CLI) is a means of interacting with a device or computer program with commands from a user or client, and responses from the device or program, in the form of lines of text.', 
  'reference': 'Wikipedia Contributors. “Command-Line Interface.” Wikipedia, Wikimedia Foundation, 13 Nov. 2019, en.wikipedia.org/wiki/Command-line_interface.'},
  { 'id':16, 
  'term': 'Enterprise system', 
  'description': 'Enterprise systems are large-scale software packages that are able to track and control all of the complex operations of a business.', 
  'reference': 'The University of Scranton. “10 Ways Enterprise Systems Affect Your Business.” The University of Scranton, 27 Apr. 2021, elearning.scranton.edu/resources/article/10-ways-enterprise-systems-affect-your-business/.'},
  { 'id':17, 
  'term': 'DevOps Cycle', 
  'description': 'The DevOps lifecycle is a continuous software development process that employs DevOps best practices to plan, build, integrate, deploy, monitor, operate, and offer continuous feedback throughout the softwares cycle.', 
  'reference': '“DevOps Lifecycle : Different Phases in DevOps.” BrowserStack, www.browserstack.com/guide/devops-lifecycle.'},
  { 'id':18, 
  'term': 'Deployment', 
  'description': 'Software deployment includes all of the steps, processes, and activities that are required to make a software system or update available to its intended users. Today, most IT organizations and software developers deploy software updates, patches and new applications with a combination of manual and automated processes. ', 
  'reference': 'Sumo Logic. “What Is Software Deployment? | Sumo Logic.” Sumo Logic, www.sumologic.com/glossary/software-deployment/.'},
  { 'id':19, 
  'term': 'Waterfall model', 
  'description': 'The Waterfall Model was the first Process Model to be introduced. It is also referred to as a linear-sequential life cycle model. It is very simple to understand and use. In a waterfall model, each phase must be completed before the next phase can begin and there is no overlapping in the phases.', 
  'reference': 'Tutorialspoint. “SDLC Waterfall Model.” Www.tutorialspoint.com, 2019, www.tutorialspoint.com/sdlc/sdlc_waterfall_model.htm.'},
  { 'id':20, 
  'term': 'Repository', 
  'description': 'A repository is a central location for storing and managing software code and files. It enables version control, collaboration, and history tracking of changes, making it essential for software projects.', 
  'reference': '“Repository (Version Control).” Wikipedia, 29 Mar. 2023, en.wikipedia.org/wiki/Repository_(version_control). Accessed 4 Aug. 2023.'},
  { 'id':21, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':22, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':23, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':24, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':25, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':26, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':27, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':28, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':29, 
  'term': '', 
  'description': '', 
  'reference': ''},
  { 'id':30, 
  'term': '', 
  'description': '', 
  'reference': ''},

  
];

/*
{ 'id':, 
'term': '', 
'description': '', 
'reference': ''},
*/

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', subtitle: 'Software Deployment and Operations Glossary', items: itemList });
});

module.exports = router;
